services: 
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    - "443:443"
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - n8n

  backend:
    image: chaitanyalohani/commitlog-backend:latest
    environment:
      PORT: 3001
      NODE_ENV: production
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MONGODB_URL: ${MONGODB_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: chaitanyalohani/commitlog-frontend:latest
    environment:
      NEXT_PUBLIC_API_URL: ${ALLOWED_ORIGINS}
      EDGE_STORE_ACCESS_KEY: ${EDGE_STORE_ACCESS_KEY}
      EDGE_STORE_SECRET_KEY: ${EDGE_STORE_SECRET_KEY}
    depends_on: 
      - backend
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=n8n.chaitanya-lohani.me
      - WEBHOOK_URL=https://n8n.chaitanya-lohani.me
      - N8N_PROTOCOL=https
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
    
  mongo:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes: 
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis: 
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
  n8n_data:
