services: 
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    restart: unless-stopped
    depends_on:
      - frontend
      - backend

  backend:
    build: 
      context: ./backend
    environment:
      PORT: 3001
      NODE_ENV: production
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MONGODB_URL: mongodb://mongo:27017/student-intership-portal
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${ALLOWED_ORIGINS}
        EDGE_STORE_ACCESS_KEY: ${EDGE_STORE_ACCESS_KEY}
        EDGE_STORE_SECRET_KEY: ${EDGE_STORE_SECRET_KEY}
    environment:
      NEXT_PUBLIC_API_URL: ${ALLOWED_ORIGINS}
      EDGE_STORE_ACCESS_KEY: ${EDGE_STORE_ACCESS_KEY}
      EDGE_STORE_SECRET_KEY: ${EDGE_STORE_SECRET_KEY}
    depends_on: 
      - backend
    restart: unless-stopped
    
  mongo:
    image: mongo:8
    restart: always
    volumes: 
      - mongo_data:/data/db

  redis: 
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
