services: 
  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80
    restart: unless-stopped


  backend:
    build: 
      context: ./backend
      args:
        ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
        REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
        ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
        ADMIN_NAME: ${ADMIN_NAME}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports: 
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: production
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      MONGODB_URL: mongodb://mongo:27017/student-intership-portal
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${ALLOWED_ORIGINS}
        EDGE_STORE_ACCESS_KEY: ${EDGE_STORE_ACCESS_KEY}
        EDGE_STORE_SECRET_KEY: ${EDGE_STORE_SECRET_KEY}
    ports: 
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${ALLOWED_ORIGINS}
      EDGE_STORE_ACCESS_KEY: ${EDGE_STORE_ACCESS_KEY}
      EDGE_STORE_SECRET_KEY: ${EDGE_STORE_SECRET_KEY}
    depends_on: 
      - backend
    restart: unless-stopped
    
  mongo:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - mongo_data:/data/db

  redis: 
    image: redis:7
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
